### ISSUE TITLE
Atleast give credits to the original Author.

### ISSUE THREAD

**Issue by imneonizer** [ashish230897/Brightness-Level-Of-an-Image#1]
Here is the original, repo
https://github.com/imneonizer/How-to-find-if-an-image-is-bright-or-dark

**Comment by ashish230897** [comment]
Hello Nitin,
Hope you are doing well!
First of all, Apologies for not giving your repository the credits that it
deserves. I must say that your repository helped me in my task and gave me
decent results after some more brainstorming. It just skipped my mind to
give appropriate credits and I too strongly believe that such practices
shouldn't be followed and is a part of plagiarism.
Thanks for informing me.
Regards,
Ashish Agrawal
